[workspace]
members = [
    "era-compiler-solidity",
    "yul-syntax-tools",
]
resolver = "2"

[workspace.package]
authors = [
    "Oleksandr Zarudnyi <a.zarudnyy@matterlabs.dev>",
    "Igor Zhirkov <iz@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
version = "1.5.3"
